### PR TITLE
Add support for pact-lsp

### PR DESCRIPTION
**Pull request by trendzetter**
adds support for auto-completion through the use of the pact-lsp

### CODE REVIEW

**Comment by trendzetter** [comment]
I'll add a checkbox in the config whether to enable this functionality or not

**Comment by trendzetter** [comment]
I think this is ready for review. There are some issues (not everything completing) with the lsp but these are probably all on the pact lsp side. I'll move on to filing issues against lsp next.

**Review by Randynamic — COMMENTED** [review]
@EnoF can you check this PR?

**Comment by EnoF** [comment]
@trendzetter looking good! 
image

**Review by EnoF — APPROVED** [review]

**Pull request merged**
